# -*- coding: utf-8 -*-
"""EjExplorador6_43.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LacGymfKqbQxvSKfodnmlqnKrfr8OqoP
"""

#Distancia
velocidad = float(input("Ingrese la velocidad en m/s: "))
tiempo = float(input("Ingrese el tiempo en segundos: "))

distancia = velocidad * tiempo
print(f"La distancia recorrida es: {distancia} metros")