# -*- coding: utf-8 -*-
"""EjExplorador9_70.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nT8hM4qjxeanGZLIW36V8EJ5K0y6EiHB
"""

#Apariciones

cadena = input("Ingrese una cadena de texto: ").lower()
palabras = cadena.split()
apariciones = {}

for palabra in palabras:
    if palabra in apariciones:
        apariciones[palabra] += 1
    else:
        apariciones[palabra] = 1

print("\nDiccionario de apariciones:")
for palabra, cantidad in apariciones.items():
    print(f"'{palabra}': {cantidad}")