# -*- coding: utf-8 -*-
"""EjExplorador8_53.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zWQHYyXb72KDYFDGwlnYQ6r-Mgx00DXl
"""

#Tornillo

tamanio_tornillo = float(input("Ingrese el tamaño del tornillo en centímetros: "))

if 1 <= tamanio_tornillo < 3:
    print("El tornillo es pequeño.")
elif 3 <= tamanio_tornillo < 5:
    print("El tornillo es mediano.")
elif 5 <= tamanio_tornillo < 6.5:
    print("El tornillo es grande.")
elif 6.5 <= tamanio_tornillo < 8.5:
    print("El tornillo es muy grande.")
elif tamanio_tornillo >= 8.5:
    print("El tornillo es gigante.")
else:
    print("El tamaño ingresado no es válido.")