# -*- coding: utf-8 -*-
"""EjExplorador12_79.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AlDKWJusDv5vlJMHN5-Qwt6UVe1ItaeZ
"""

#Filtrado con pandas

import pandas as pd

# Paso 1
url_iris = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris = pd.read_csv(url_iris, header=None, names=['sepal_length', 'sepal_width', 'petal_length', 'petal_width', 'species'])

# Paso 2
print("Primeras 5 filas del DataFrame:")
print(iris.head())

# Paso 3
print("\nFiltrando las filas donde la especie es 'setosa':")
setosa_data = iris[iris['species'] == 'Iris-setosa']
print(setosa_data)

# Paso 4
media_longitud_sepalos = setosa_data['sepal_length'].mean()
print(f"\nMedia de la longitud de los sépalos para la especie 'setosa': {media_longitud_sepalos}")