# -*- coding: utf-8 -*-
"""EjExplorador12_78.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16d_xC5bcLA3FkLeoYMMp2GofBIh6vAyu
"""

#Operaciones basicas con NumPy

import numpy as np

# Paso 1
vector = np.array([1, 2, 3, 4, 5])

# Paso 2
media = np.mean(vector)
desviacion_estandar = np.std(vector)
print(f"Media del vector: {media}")
print(f"Desviación Estándar del vector: {desviacion_estandar}")

# Paso 3
matriz = np.random.randint(1, 11, size=(3, 2))

# Paso 4
matriz_multiplicada = matriz * 2

# Paso 5
print("\nMatriz Multiplicada por 2:")
print(matriz_multiplicada)