# -*- coding: utf-8 -*-
"""EjExplorador6_46.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kqGiwYKsnIyVGIuelAxRor5624oesLpi
"""

#Validacion contraseña
contrasena = input("Ingrese su contraseña: ")
es_valida = len(contrasena) >= 8 and any(char.isdigit() for char in contrasena)
print(f"¿La contraseña es válida? {es_valida}")