# -*- coding: utf-8 -*-
"""EjExplorador9_74.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16RIGpJdIFkMO8ANAdPgjnBEFnAJKnFGn
"""

#Registro de Empleados

empleados = []

while True:
    print("Menú:")
    print("1. Añadir Empleado")
    print("2. Mostrar Todos los Empleados")
    print("3. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        nombre = input("Ingrese el nombre del empleado: ")
        salario = float(input("Ingrese el salario del empleado: "))
        cargo = input("Ingrese el cargo del empleado: ")
        empleado = {"Nombre": nombre, "Salario": salario, "Cargo": cargo}
        empleados.append(empleado)
    elif opcion == "2":
        print("Lista de Empleados:")
        for emp in empleados:
            print(emp)
    elif opcion == "3":
        print("Saliendo del programa...")
        break
    else:
        print("Opción no válida. Inténtelo de nuevo.")