# -*- coding: utf-8 -*-
"""EjExplorador9_68.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1x1DK2SbO-UPhZO-lkQZrQX8Dl94FMjyM
"""

#Materias

asignaturas = ["Matemáticas", "Física", "Química", "Historia", "Lenguaje", "Programacion"]
notas = []

for asignatura in asignaturas:
    nota = float(input(f"Ingrese la nota de {asignatura}: "))
    notas.append(nota)

print("\nResumen de notas:")
for i in range(len(asignaturas)):
    print(f"En {asignaturas[i]} has sacado {notas[i]}")