# -*- coding: utf-8 -*-
"""EjExplorador9_66.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bmuxOzHMDk-StCMiQRGkkWjHaZiLeHC8
"""

#Inversion

cantidad_invertir = float(input("Ingrese la cantidad a invertir: "))
interes_anual = float(input("Ingrese el interés anual (%): "))
num_anios = int(input("Ingrese el número de años: "))

for anio in range(1, num_anios + 1):
    cantidad_invertir *= 1 + (interes_anual / 100)
    print(f"Año {anio}: Capital acumulado = {round(cantidad_invertir, 2)}")