# -*- coding: utf-8 -*-
"""EjExplorador6_40.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WfbhoIyUywNaVQ0QsxYcn5DW28RI8qdc
"""

#Operaciones
num1 = float(input("Ingrese el primer número: "))
num2 = float(input("Ingrese el segundo número: "))

suma = num1 + num2
resta = num1 - num2
multiplicacion = num1 * num2

print(f"La suma de los números es: {suma}")
print(f"La resta de los números es: {resta}")
print(f"La multiplicación de los números es: {multiplicacion}")