# -*- coding: utf-8 -*-
"""EjExplorador12_80.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Xu97hsTqiBu6DvIEELKfzPfoy5PqrLwi
"""

#Concatenacion de Dataframe

import pandas as pd

# Paso 1
df1 = pd.DataFrame({'A': [1, 2, 3], 'B': [4, 5, 6], 'C': [7, 8, 9]})
df2 = pd.DataFrame({'A': [10, 11, 12], 'B': [13, 14, 15], 'C': [16, 17, 18]})

# Paso 2
print("DataFrame 1:")
print(df1)
print("\nDataFrame 2:")
print(df2)

# Paso 3
df_concat = pd.concat([df1, df2])

# Paso 4
print("\nResultado de la Concatenación:")
print(df_concat)