# -*- coding: utf-8 -*-
"""EjExplorador9_65.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d2h5KQTPVyRZ31Olei6YvA5Xumkrp6X8
"""

#Letra en frase

frase = input("Ingrese una frase: ").lower()
letra = input("Ingrese una letra: ").lower()

if len(letra) == 1 and letra.isalpha():
    cantidad_apariciones = frase.count(letra)
    print(f"La letra '{letra}' aparece {cantidad_apariciones} veces en la frase.")
else:
    print("Entrada no válida. Por favor, ingrese una letra.")