# -*- coding: utf-8 -*-
"""EjExplorador9_69.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kr2crBSBo8r0EyQHcKW9Idxq4ouGTcH2
"""

#Cesta de compras

cesta = {}
while True:
    articulo = input("Ingrese el nombre del artículo (o 'FIN' para finalizar): ")
    if articulo.upper() == "FIN":
        break
    precio = float(input(f"Ingrese el precio de {articulo}: "))
    cesta[articulo] = precio

print("\nLista de la compra:")
total = 0
for articulo, precio in cesta.items():
    print(f"{articulo}\t{precio}")
    total += precio

print(f"\nTOTAL\t{total}")