# -*- coding: utf-8 -*-
"""EjExplorador6_39.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jxeRoaYDZPzCECwZpgAAtHaaztO9tEko
"""

#Buen camino
nombre = input("Ingrese su nombre: ")
edad = input("Ingrese su edad: ")

print(f"Vas por buen camino, {nombre} ({edad} años).")