# -*- coding: utf-8 -*-
"""EjExplorador8_59.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15a4OA3yHdDrX7hzfGpEY7r2eAKaEDC-D
"""

#Multiplicacion

multiplicacion = 1

while True:
    num = int(input("Ingrese un número (mayor a 10 para terminar): "))
    if num > 10:
        break
    multiplicacion *= num

print(f"La multiplicación de los números ingresados es: {multiplicacion}")