# -*- coding: utf-8 -*-
"""EjExplorador6_47.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S_P3oTQGYCpQ6bb4Z7uA8LtMkgXl0S33
"""

#Validacion rango
numero = int(input("Ingrese un número: "))
en_rango = 10 <= numero <= 20
print(f"¿El número está en el rango de 10 a 20? {en_rango}")