# -*- coding: utf-8 -*-
"""EjExplorador8_62.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Cwt0rMMAzadIQ0McB87NUSSxC3CoQRhb
"""

#Tablas de multiplicar

numero = int(input("Ingrese un número menor a 10: "))
desde = int(input("Ingrese desde qué número quiere ver la tabla: "))
hasta = int(input("Ingrese hasta qué número quiere ver la tabla: "))

if numero < 10:
    for i in range(desde, hasta + 1):
        print(f"{numero} * {i} = {numero * i}")
else:
    print("Número fuera del rango.")