# -*- coding: utf-8 -*-
"""EjExplorador8_57.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dV2aTGJRopX4ZjqC0rl9u7yCY5YZ6NTw
"""

#Factorial

import math

while True:
    num = int(input("Ingrese un número mayor que 0 y menor que 20: "))
    if 0 < num < 20:
        print(f"El factorial de {num} es: {math.factorial(num)}")
        break
    else:
        print("Número fuera del rango. Intente de nuevo.")