# -*- coding: utf-8 -*-
"""EjExplorador9_75.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bc8sPg6gs2ZRpsPI4pyenLbd_ErwKMgf
"""

#Conversor de temperatura

def celsius_a_fahrenheit(celsius):
    return (celsius * 9/5) + 32

def fahrenheit_a_celsius(fahrenheit):
    return (fahrenheit - 32) * 5/9

while True:
    print("Menú:")
    print("1. Convertir de Celsius a Fahrenheit")
    print("2. Convertir de Fahrenheit a Celsius")
    print("3. Salir")

    opcion = input("Seleccione una opción: ")

    if opcion == "1":
        celsius = float(input("Ingrese la temperatura en Celsius: "))
        resultado = celsius_a_fahrenheit(celsius)
        print(f"Resultado: {resultado} °F")
    elif opcion == "2":
        fahrenheit = float(input("Ingrese la temperatura en Fahrenheit: "))
        resultado = fahrenheit_a_celsius(fahrenheit)
        print(f"Resultado: {resultado} °C")
    elif opcion == "3":
        print("Saliendo del programa...")
        break
    else:
        print("Opción no válida. Inténtelo de nuevo.")