# -*- coding: utf-8 -*-
"""EjExplorador8_63.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C7FSnpgvANXN-d2YWifeJAFFWPjpDrPi
"""

#Apilable

numero = int(input("Ingrese un número natural: "))
triangular = 0
nivel = 0

while triangular < numero:
    nivel += 1
    triangular = (nivel * (nivel + 1)) // 2

if triangular == numero:
    print(f"{numero} es adecuado para apilar.")
else:
    print(f"{numero} no es adecuado para apilar.")