# -*- coding: utf-8 -*-
"""EjExplorador6_48.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gJVT3J1E21MKj-vEOCCjObTed3cnrU3g
"""

#Comparacion de cadenas

cadena1 = input("Ingrese la primera cadena: ")
cadena2 = input("Ingrese la segunda cadena: ")

son_iguales = cadena1 == cadena2
print(f"¿Las cadenas son iguales? {son_iguales}")