# -*- coding: utf-8 -*-
"""EjExplorador8_56.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OfYFSqPAKSkzmjlVsXK3HQw0xAymgEV4
"""

#Dia de la semana

dia_semana = input("Ingrese un día de la semana: ").lower()

if dia_semana in ["lunes", "sábado", "domingo"]:
    print(f"Es {dia_semana}. ¡Buen día!")
elif dia_semana == "viernes":
    print(f"Es {dia_semana}. Ya vemos cerca el fin de semana.")
else:
    print(f"Avancemos que ya es {dia_semana}.")