# -*- coding: utf-8 -*-
"""EjExplorador9_67.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQSaEjJFKZVelOYyMtU0Mj_S_9u6F62P
"""

#Triangulo Rectangulo

altura = int(input("Ingrese un número entero para la altura del triángulo: "))

for i in range(1, altura + 1, 2):
    for j in range(i, 0, -2):
        print(j, end=" ")
    print()