# -*- coding: utf-8 -*-
"""EjExplorador8_64.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Jz77yy7__H7EZnOSg0V31S4xCawSZu4I
"""

#Fibonacci

def fibonacci(n):
    fib = [0, 1]
    while len(fib) < n:
        fib.append(fib[-1] + fib[-2])
    return fib

cantidad_elementos = int(input("Ingrese el número de elementos de la serie Fibonacci: "))
resultado = fibonacci(cantidad_elementos)
print(f"Los primeros {cantidad_elementos} elementos de la serie Fibonacci son: {resultado}")