# -*- coding: utf-8 -*-
"""EjExplorador6_38.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e3L1ZZ87MgbdxT1RwHG4fCrRUZb_zZf_
"""

#Media de 3 numeros
num1 = float(input("Ingrese el primer número: "))
num2 = float(input("Ingrese el segundo número: "))
num3 = float(input("Ingrese el tercer número: "))

media = (num1 + num2 + num3) / 3
print(f"La media de los números es: {media}")