# -*- coding: utf-8 -*-
"""EjExplorador6_49.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wypolwWFVO5TeHhy6FR8wEQDcoGVRo8Z
"""

#Par-impar

numero = int(input("Ingrese un número entero: "))
es_par = numero % 2 == 0
print(f"El número ingresado es {'par' if es_par else 'impar'}.")