# -*- coding: utf-8 -*-
"""EjExplorador8_52.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yXlh9pwt-FdYyt9T6Ey7nmHePm74d0jv
"""

#Tipo de triangulo

lado1 = float(input("Ingrese la longitud del primer lado del triángulo: "))
lado2 = float(input("Ingrese la longitud del segundo lado del triángulo: "))
lado3 = float(input("Ingrese la longitud del tercer lado del triángulo: "))

if lado1 == lado2 == lado3:
    tipo = "equilátero"
elif lado1 == lado2 or lado1 == lado3 or lado2 == lado3:
    tipo = "isósceles"
else:
    tipo = "escaleno"

print(f"El triángulo es {tipo}.")