# -*- coding: utf-8 -*-
"""EjExplorador6_41.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14gWsg13wb8JsRZy6jiCN31zKQocsY58V
"""

#Horas trabajadas
horas_trabajadas = float(input("Ingrese el número de horas trabajadas: "))
costo_por_hora = float(input("Ingrese el costo por hora: "))

pago_total = horas_trabajadas * costo_por_hora
print(f"El pago que le corresponde es: {pago_total}")