# -*- coding: utf-8 -*-
"""EjExplorador9_72.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10-kZvRKyRgDJidQEqKCs1Um6SrnHmRzV
"""

#Promedio

notas = []
while True:
    nota = float(input("Ingrese una nota (o -1 para salir): "))
    if nota == -1:
        break
    notas.append(nota)

if notas:
    promedio = sum(notas) / len(notas)
    print(f"El promedio de las notas es: {promedio}")
else:
    print("No se ingresaron notas.")