# -*- coding: utf-8 -*-
"""EjExplorador8_55.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svpWXYkT1bgAvvsGEnTqb59gGMFXhePV
"""

#Area

opcion = input("¿Quiere calcular el área de un triángulo (T) o de un círculo (C)? ").lower()

if opcion == "t":
    base = float(input("Ingrese la base del triángulo: "))
    altura = float(input("Ingrese la altura del triángulo: "))
    area = 0.5 * base * altura
elif opcion == "c":
    radio = float(input("Ingrese el radio del círculo: "))
    area = 3.1416 * radio ** 2
else:
    print("Opción no válida.")
    area = None

if area is not None:
    print(f"El área calculada es: {area}")